name: cleanup
on:
  schedule:
    - cron: "0 0 * * 0" # weekly, cf.: https://crontab.guru/every-week
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup old releases
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          #repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 3
          keep_min_download_counts: 0 # Optional parameters
          delete_expired_data: 10 # Optional parameters
          delete_tags: true # Optional parameters
          #delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
