name: release
on:
  # TODO: For now also enable manual runs
  workflow_dispatch:
  # listen to repository dispatch events from jn-fork
  repository_dispatch:
    types: [update-jn-release]

jobs:
  release:
    name: Update app cast
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Patch appcast
        working-directory: release/_scripts/
        env:
          JN_VERSION: ${{ github.event.client_payload.version }}
          JN_SIGNATURE: ${{ github.event.client_payload.signature }}
          JN_RELEASE_FEATURES: "TODO"
          JN_RELEASE_BUGFIXES: "TODO"
        run: |
          echo "Creating sparkle entry for JammerClient '$JN_VERSION'"
          python3 sparkle.py
          ls -la ..
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "releases"
          default_author: github_actor
          author_name: Digital Stage
          author_email: contact@digital-stage.org
          message: "Add release for ${{ github.event.client_payload.version }}"
